name: pawsmatch
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  firebase_analytics: ^11.4.0
  cloud_firestore: ^5.6.1
  file_picker: ^5.0.1
  intl: ^0.20.1
  supabase_flutter: ^2.8.3
  flutter_dotenv: ^5.0.2
  image_picker: ^1.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
