buildscript {    // Use a Kotlin version compatible with Java 8
    ext.kotlin_version = '1.8.20'
    
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://storage.googleapis.com/download.flutter.io"
        }
    }

    dependencies {
        classpath 'com.google.gms:google-services:4.3.15'
        classpath 'com.android.tools.build:gradle:8.2.1'
        // Make sure we also have this dependency with the updated version
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

plugins {
    // Add the dependency for the Google services Gradle plugin with the correct version
    id("com.google.gms.google-services") version "4.3.15" apply false
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://storage.googleapis.com/download.flutter.io"
        }
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
