// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDgXwNr_AD4ez4xXlIAnUCL0BdqOPJ2dA',
    appId: '1:572309199876:web:319ca6fe9872a5d1d6a951',
    messagingSenderId: '572309199876',
    projectId: 'pawsmatch-c5390',
    authDomain: 'pawsmatch-c5390.firebaseapp.com',
    databaseURL: 'https://pawsmatch-c5390-default-rtdb.firebaseio.com',
    storageBucket: 'pawsmatch-c5390.firebasestorage.app',
    measurementId: 'G-RZ3PEXMPTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOJcTqEMKRTC95Va-4xw7uupYhy4DmHpc',
    appId: '1:572309199876:android:60adf561a8d26d9bd6a951',
    messagingSenderId: '572309199876',
    projectId: 'pawsmatch-c5390',
    databaseURL: 'https://pawsmatch-c5390-default-rtdb.firebaseio.com',
    storageBucket: 'pawsmatch-c5390.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQJcNbNLHfceMcuPfAHOnUutPrEcZFp38',
    appId: '1:572309199876:ios:37ecd9fd42964182d6a951',
    messagingSenderId: '572309199876',
    projectId: 'pawsmatch-c5390',
    databaseURL: 'https://pawsmatch-c5390-default-rtdb.firebaseio.com',
    storageBucket: 'pawsmatch-c5390.firebasestorage.app',
    iosBundleId: 'com.example.pawsmatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQJcNbNLHfceMcuPfAHOnUutPrEcZFp38',
    appId: '1:572309199876:ios:37ecd9fd42964182d6a951',
    messagingSenderId: '572309199876',
    projectId: 'pawsmatch-c5390',
    databaseURL: 'https://pawsmatch-c5390-default-rtdb.firebaseio.com',
    storageBucket: 'pawsmatch-c5390.firebasestorage.app',
    iosBundleId: 'com.example.pawsmatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDgXwNr_AD4ez4xXlIAnUCL0BdqOPJ2dA',
    appId: '1:572309199876:web:eab60fe59967ec44d6a951',
    messagingSenderId: '572309199876',
    projectId: 'pawsmatch-c5390',
    authDomain: 'pawsmatch-c5390.firebaseapp.com',
    databaseURL: 'https://pawsmatch-c5390-default-rtdb.firebaseio.com',
    storageBucket: 'pawsmatch-c5390.firebasestorage.app',
    measurementId: 'G-CF9G12PZVD',
  );

}