name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - deployment
      - setup-github-actions

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.5.3'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter web app
      run: flutter build web

    - name: Deploy to Firebase Hosting
      env:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PAWSMATCH_C5390 }}"
      run: firebase deploy --only hosting