name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
      - development
      - setup-github-actions

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.2'  # Change this to match your Flutter version

    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter web app
      run: |
        flutter build web --release \
        --dart-define=FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} \
        --dart-define=FIREBASE_APP_ID_WEB=${{ secrets.FIREBASE_APP_ID_WEB }} \
        --dart-define=FIREBASE_APP_ID_WINDOWS=${{ secrets.FIREBASE_APP_ID_WINDOWS }} \
        --dart-define=FIREBASE_APP_ID_MACOS=${{ secrets.FIREBASE_APP_ID_MACOS }} \
        --dart-define=FIREBASE_APP_ID_ANDROID=${{ secrets.FIREBASE_APP_ID_ANDROID }} \
        --dart-define=FIREBASE_APP_ID_IOS=${{ secrets.FIREBASE_APP_ID_IOS }} \
        --dart-define=FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }} \
        --dart-define=FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} \
        --dart-define=FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }} \
        --dart-define=FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }} \
        --dart-define=FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }} \
        --dart-define=FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }} \
        --dart-define=FIREBASE_IOS_BUNDLE_ID=${{ secrets.FIREBASE_IOS_BUNDLE_ID }} \
        --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
        --dart-define=SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}

    - name: Set up Firebase CLI
      run: |
        curl -sL https://firebase.tools | bash
        firebase --version

    - name: Authenticate with Firebase
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PAWSMATCH_C5390 }}
      run: |
        echo "$FIREBASE_SERVICE_ACCOUNT" > "${HOME}/firebase-key.json"
        export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/firebase-key.json"
        firebase functions:config:set service_account="$(cat ${HOME}/firebase-key.json)"
        firebase use --project "$(jq -r '.project_id' ${HOME}/firebase-key.json)"
  
    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting --token "$(jq -r '.token' ${HOME}/firebase-key.json)"